### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by mesteryui** [catppuccin/zen-browser#6]
When I access to menus and buttons of a more specific way appears of this way
![imagen](https://github.com/user-attachments/assets/62c84643-7a90-4748-bd87-9b26786c14e8)

**Comment by IAmJafeth** [comment]
Hi @mesteryui 

First of all, what a gorgeous desktop you have there, I love it! 😍 Hope to see your post in [r/unixporn](https://www.reddit.com/r/unixporn) soon!

And thanks for your report, I am not a home rn, but I will check this as soon as I have some time (hopefully by the end of day)
