### ISSUE TITLE
Newest a.16 update breaks theming.

### ISSUE THREAD

**Issue by undefinedcode0** [catppuccin/zen-browser#9]
After updating zen-browser. I noticed that some of the elements were unthemed, the only one I know so far is this:
![image](https://github.com/user-attachments/assets/c23bf54b-dacf-450c-a338-17ac5c985d23)
I'm not experienced in theming, so I am unaware of whats causing this issue. Any further assistance is greatly appreciated.

**Comment by IAmJafeth** [comment]
Hi @undefinedcode0,

I just updated my Zen Browser to latest a.16 version, however I see no impact on my Catppuccin Setup:

![image](https://github.com/user-attachments/assets/7b33603a-e429-4e57-8c69-fc7b506a62af)

Could please confirm if you have any theme Zen Mod installed? (try disabling all mods, to see if this gets resolved)
Or have you been tinkering with the new Zen's Customize Theme option?

**Comment by undefinedcode0** [comment]
> Hi @undefinedcode0,
> 
> I just updated my Zen Browser to latest a.16 version, however I see no impact on my Catppuccin Setup:
> 
> ![image](https://github.com/user-attachments/assets/7b33603a-e429-4e57-8c69-fc7b506a62af)
> 
> Could please confirm if you have any theme Zen Mod installed? (try disabling all mods, to see if this gets resolved)
> Or have you been tinkering with the new Zen's Customize Theme option? 

No, I don't have additional Zen Mods installed. I kept the theming as is and I have not tinkered with it.

**Comment by undefinedcode0** [comment]
Not sure if this will help but, every time I relaunch the browser. The theming works perfectly fine until the selected page is loaded. https://i.imgur.com/t6bXzo2.gif

**Comment by IAmJafeth** [comment]
Mmmm, based on that behavior it seems there is some CSS overwriting the Catppuccin Theme.

What I can see is that: 
1. Catppuccin Theme loads first
2. Then a second CSS overwrites it once Zen fully loads.

That is why we see it flashing for a second there.

I have tested with a brand new profile as well on my end and no issues could be found.

## Troubleshooting

### Browser Theme

Make sure you have selected the Dark (or light if you would like to use Latte)  theme selected in your Zen Browser, you can view it in `about:addons` > Themes

![image](https://github.com/user-attachments/assets/ebca98ff-069b-4b88-a58b-5744eecd7596)

### Custom CSS / Mod / Custom Theme

To discard any possible custom CSS affecting the browser can you test the theme in a **Brand New** Zen Profile?

You can click on your Profile Picture in the Zen Toolbar and click the "+" symbol to create it. 

![image](https://github.com/user-attachments/assets/b0d5f2fe-8844-4cd4-bef0-732d7d50e721)

Then apply the Catppuccin Theme to this profile, if it works, then this tell us there could be some custom CSS, Mod or Theme affecting your Catppuccin Theme

Let me know the results!

**Comment by undefinedcode0** [comment]
> Mmmm, based on that behavior it seems there is some CSS overwriting the Catppuccin Theme.
> 
> What I can see is that:
> 
>     1. Catppuccin Theme loads first
> 
>     2. Then a second CSS overwrites it once Zen fully loads.
> 
> 
> That is why we see it flashing for a second there.
> 
> I have tested with a brand new profile as well on my end and no issues could be found.
> ## Troubleshooting
> ### Browser Theme
> 
> Make sure you have selected the Dark (or light if you would like to use Latte) theme selected in your Zen Browser, you can view it in `about:addons` > Themes
> 
> ![image](https://private-user-images.githubusercontent.com/45522320/382152734-ebca98ff-069b-4b88-a58b-5744eecd7596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjQwMDksIm5iZiI6MTczMDQyMzcwOSwicGF0aCI6Ii80NTUyMjMyMC8zODIxNTI3MzQtZWJjYTk4ZmYtMDY5Yi00Yjg4LWE1OGItNTc0NGVlY2Q3NTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAxMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZjllZTM3MmVhZDFmZmE4YmZhMjdmZTRlNTliMzFiODdjYzJmYjI2ZmQ3OTE0ODg5MjdlY2RmNmNhZmY5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0uorMHA0rfBDJHye9qoizmSKAeNU-picnOwjOXeae0s)
> ### Custom CSS / Mod / Custom Theme
> 
> To discard any possible custom CSS affecting the browser can you test the theme in a **Brand New** Zen Profile?
> 
> You can click on your Profile Picture in the Zen Toolbar and click the "+" symbol to create it.
> 
> ![image](https://private-user-images.githubusercontent.com/45522320/382152369-b0d5f2fe-8844-4cd4-bef0-732d7d50e721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjQwMDksIm5iZiI6MTczMDQyMzcwOSwicGF0aCI6Ii80NTUyMjMyMC8zODIxNTIzNjktYjBkNWYyZmUtODg0NC00Y2Q0LWJlZjAtNzMyZDdkNTBlNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAxMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjk5ZTI5MTE2NGYxMjhhNDNmOTlhMjViYjg3NWVhYTgzNzhjZjZhN2JkZjQ1NTcwNTMwNTE2YjU1M2Q4NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GAc8reCSXQJr9tP7Daykpguzj9PewgsSyCV8r5p2THI)
> 
> Then apply the Catppuccin Theme to this profile, if it works, then this tell us there could be some custom CSS, Mod or Theme affecting your Catppuccin Theme
> 
> Let me know the results!

Yes, I had made sure I'm using dark mode for the 'mocha' theme. After applying the theme to a new profile. The theming issue still persists either way. The only temporary fix I know of is switching Dark mode off and on.

**Comment by undefinedcode0** [comment]
Something that I recently discovered is that opening a Private Window fixes the CSS override issue. I'm not sure what is overriding CSS, but I'll look into it.
![image](https://github.com/user-attachments/assets/537b2502-7e00-427c-817a-db36bd67cb5a)

**Comment by undefinedcode0** [comment]
After looking more further into the root directory of my profile folder, `userContent.css` and `userChrome.css` seem to be the only `*.css` files present.

**Comment by IAmJafeth** [comment]
Thanks for your reports @undefinedcode0 @SolsticeSpectrum ,

It finally affected me as well, so I do not have to make guesses anymore: 

![image](https://github.com/user-attachments/assets/1f71dc23-483b-4335-8bac-41afc988ad92)

Interestingly only on MacOS, Linux seems to be working fine so far.

Now I am curious, what platform are you on? 

I will take a look at this later today, probably pushing an update tonight.

**Comment by undefinedcode0** [comment]
Im on Windows 10 IoT LTSC 21h2 x64

**Comment by cswimr** [comment]
Can confirm this is also happening to me on Linux (Arch, KDE Plasma 6.2, Wayland - if any of that matters), but switching to another theme in `about:addons` then back to the default Dark theme fixes it for me as well.

**Comment by SolsticeSpectrum** [comment]
I am on Windows 11

**Comment by IAmJafeth** [comment]
Hey everyone!

Just pushed an update that should fix this issue, please test it and let me know your results.
